version: '2'
services:
    web:
        build: .
        restart: always
        ports:
            - '5000:5000'
        volumes:
            - .:/src
        command: python3 manage.py runserver 0.0.0.0:5000
        depends_on:
            - db
    db:
        image: postgres